version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/scholarships_db
      - DB_HOST=db
      - DB_PORT=5432
      - REGION=us-east-1
      - USER_POOL_ID=
      - CLIENT_ID=
      - FRONTEND_URL=http://localhost:3000
      - QUEUE_URL=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=      
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scholarships_db
    ports:
      - "5432:5432"
